name: A workflow for my Hello World file
on: push
jobs:
  action1:
    name: Hello World action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./action-a
        with:
          MY_NAME: "shun"
